import 'package:get/get.dart';

class Langauges extends Translations{

  Map<String ,Map<String,String>> get keys=>{
     'en_US' :{
       'Username' : 'Username',
        'Password' : 'Password',
       'Create account':'Create account',
       'FNB account number': 'FNB account number',
       'Login Successful' : 'Login Successful',
       'Please enter your name & password!':'Please enter your name & password!',
       'You entered incorrect username or password, please try again!':'You entered incorrect username or password, please try again!',
       'Login':'Login',
       'Register new user':'Register new user',
       'FAQs\nretail':'FAQs\nretail',
       '  Foreign\nExchange':'  Foreign\nExchange',
       ' ATM/Branch\n     Locator':' ATM/Branch\n     Locator',
       'Contact\n     us':'Contact\n     us',
       'Authentication':'Authentication',
       'Choose the authentication type to log-in':'Choose the authentication type to log-in',
       'Face id':'Face id',
       'otp sent!':'otp sent!',
       'invalid email!':'invalid email!',
       'OTP':'OTP',
       'OTP authentication':'OTP authentication',
       'A verification code has been sent to':'A verification code has been sent to',
       'Welcome ☺':'Welcome ☺',
       'Incorrect OTP!':'Incorrect OTP!',
       'Confirm':'Confirm',
       'Error':'Error',
       'Success':'Success',
       'Acceptable process!':'Acceptable process!',
       'error':'error',
       'Certificate':'Certificate',
       'Select product':'Select product',
       'Amount':'Amount',
       'Enter your password (4 digits)':'Enter your password (4 digits)',
       'Start date':'Start date',
       'I have read and agree to the terms\nof FNB services':'I have read and agree to the terms\nof FNB services',
       'Are you sure you want to apply for this certificate informations?':'Are you sure you want to apply for this certificate informations?',
       'Yes':'Yes',
       'Acceptable process!':'Acceptable process!',
       'No enough balance in your account!':'No enough balance in your account!',
       'Incorrect password':'Incorrect password',
       'Please fill-in the form and agree to the terms!':'Please fill-in the form and agree to the terms!',
       'Apply':'Apply',
       'Already Exists':'Already Exists',
       'Change password':'Change password',
       'Current password':'Current password',
       'New password':'New password',
       'Confirm password':'Confirm password',
       'Password changed successfully':'Password changed successfully',
       'Please fill in the form!':'Please fill in the form!',
       'The old password is not correct':'The old password is not correct',
       'Please check that you entered data correctly!':'Please check that you entered data correctly!',
       'Save changes':'Save changes',
       'Please verify your identity':'Please verify your identity',
       'Account created successfully!':'Account created successfully!',
       'Please check that you entered the confirm password correctly!':'Please check that you entered the confirm password correctly!',
       'Please agree to the terms and conditions of FNB services!':'Please agree to the terms and conditions of FNB services!',
       'You miss to enter something!':'You miss to enter something!',
       'Please check that you entered the confirm password correctly and agree to the terms and conditions of FNB services!':'Please check that you entered the confirm password correctly and agree to the terms and conditions of FNB services!',
       'Something is wrong!':'Something is wrong!',
       'Create':'Create',
       'Currencies':'Currencies',
       'Exhange rates':'Exhange rates',
       'Currency converter':'Currency converter',
       'Home':'Home',
       'Payments':'Payments',
       'Profile':'Profile',
       'Currency Converter':'Currency Converter',
       'Input Value to Convert':'Input Value to Convert',
       'From':'From',
       'To':'To',
       'Result':'Result',
       'Term Deposit Calculator':'Term Deposit Calculator',
       'How much would you like to deposit?':'How much would you like to deposit?',
       'Amount':'Amount',
       'Duration (months)':'Duration (months)',
       'Interest rate (%)':'Interest rate (%)',
       'Calculate':'Calculate',
       'Future University in Egypt':'Future University in Egypt',
       'British University in Egypt':'British University in Egypt',
       'Ahram Canadian University':'Ahram Canadian University',
       'Ain shams University':'Ain shams University',
       'Alexandria':'Alexandria',
       'American University in Egypt':'American University in Egypt',
       'Cairo University':'Cairo University',
       'Al Azhar University':'Al Azhar University',
       'Badr University':'Badr University',
       'accnum':'accnum',
       'balance':'balance',
       'Education':'Education',
       'Education name':'Education name',
       'Student National ID':'Student National ID',
       'Purpose':'Purpose',
       'Enter your password (4 digits)':'Enter your password (4 digits)',
       'Are you sure you want to transfer on your own responsibility?':'Are you sure you want to transfer on your own responsibility?',
       'Not enough balance in your account!':'Not enough balance in your account!',
       'Incorrect password':'Incorrect password',
       'Please fill-in the form!':'Please fill-in the form!',
       'Transfer':'Transfer',
       'Injas Electricity':'Injas Electricity',
       'Canal Electricity':'Canal Electricity',
       'Middle Egypt Electricity':'Middle Egypt Electricity',
       'North Delta Electricity':'North Delta Electricity',
       'North Cairo Electricity':'North Cairo Electricity',
       'South Delta Electricity':'South Delta Electricity',
       'Electricity':'Electricity',
       'Service provider':'Service provider',
       'Your electricity code number':'Your electricity code number',
       'Egyptian pound exchange':'Egyptian pound exchange',
       'Input value in egyptian pound':'Input value in egyptian pound',
       'Sell':'Sell',
       'Buy':'Buy',
       'Call us':'Call us',
       'tel':'tel',
       'cant launch this url':'cant launch this url',
       'Call':'Call',
       'accountnumber':'accountnumber',
       'FAQs - Retail':'FAQs - Retail',
       'Can i change my user iD?':'Can i change my user iD?',
       'You can not change your user ID':'You can not change your user ID',
       'When can i use FNB app?':'When can i use FNB app?',
       'FNB app is available 24/7':'FNB app is available 24/7',
       'Can the "Login password" be changed?':'Can the "Login password" be changed?',
       'Yes, you can change the "Login password" by clicking on the settings then Change password':'Yes, you can change the "Login password" by clicking on the settings then Change password',
       'How can i login via One-Time-Password?':'How can i login via One-Time-Password?',
       'Once you clicking on the OTP option you will receive 4 digits through your mobile number, enter these digits on the textfield to login':'Once you clicking on the OTP option you will receive 4 digits through your mobile number, enter these digits on the textfield to login',
       'Can i change my personal information through the application?':'Can i change my personal information through the application?',
       'No, you can not update/change you personal information unless you go to any bank branch':'No, you can not update/change you personal information unless you go to any bank branch',
       'Can i cancel the book appointment to visit a branch?':'Can i cancel the book appointment to visit a branch?',
       'Yes, you can cancel your request anytime':'Yes, you can cancel your request anytime',
       'Can transfers be made to other accounts inside or outside FNB?':'Can transfers be made to other accounts inside or outside FNB?',
       'You can transfer to FNB accounts only':'You can transfer to FNB accounts only',
       'Ok':'Ok',
       'TAQA GAS':'TAQA GAS',
       'Gastec':'Gastec',
       'Master Gas':'Master Gas',
       'Gas':'Gas',
       'Fawry account number':'Fawry account number',
       'Current reading':'Current reading',
       'Queuing request':'Queuing request',
       'Deposit calculator':'Deposit calculator',
       'Newsroom':'Newsroom',
       'Locations':'Locations',
       'Settings':'Settings',
       'Accounts':'Accounts',
       'Cards':'Cards',
       'Loans':'Loans',
       'Certificates':'Certificates',
       'Account':'Account',
       'Enter your pass':'Enter your pass',
       'My card':'My card',
       'Credit':'Credit',
       'Name':'Name',
       'Cards offers':'Cards offers',
       'Debit':'Debit',
       'Maximum Credit Limit : 250,000 EGP':'Maximum Credit Limit : 250,000 EGP',
       'Grace period : up to 57 days for purchase':'Grace period : up to 57 days for purchase',
       'Gold':'Gold',
       'Maximum Credit Limit : 100,000 EGP':'Maximum Credit Limit : 100,000 EGP',
       'Online card usage : available':'Online card usage : available',
       'Card usage : locally and abroad':'Card usage : locally and abroad',
       'Loan amount calculator':'Loan amount calculator',
       'Loan installment calculator':'Loan installment calculator',
       'My loans requests':'My loans requests',
       'Time to invest!':'Time to invest!',
       'It seems that you dont have any investment products yet!':'It seems that you dont have any investment products yet!',
       'Apply':'Apply',
       'My certificates':'My certificates',
       'Your loan request has been uploaded successfully please wait for the response that shows in your notification page!':'Your loan request has been uploaded successfully please wait for the response that shows in your notification page!',
       'Already Exists':'Already Exists',
       'Your maximum requests for loans are 3, you need to visit your nearest branch to solve this problem!':'Your maximum requests for loans are 3, you need to visit your nearest branch to solve this problem!',
       'Loan amount':'Loan amount',
       'Min 5000 EGP':'Min 5000 EGP',
       'Max 1,500,000 EGP':'Max 1,500,000 EGP',
       'Loan period':'Loan period',
       'Min 6 months':'Min 6 months',
       'Max 120 months':'Max 120 months',
       'Interest rate (Annual %)':'Interest rate (Annual %)',
       'Min 16%':'Min 16%',
       'Max 21%':'Max 21%',
       'please check the constraints of the form!':'please check the constraints of the form!',
       'Your monthly payments':'Your monthly payments',
       'Total payable':'Total payable',
       'Total interest':'Total interest',
       '* Please note that your maximum requests for loans are 3 times':'* Please note that your maximum requests for loans are 3 times',
       'Your loan request has been uploaded successfully please wait for the response that shows in your notification page!':'Your loan request has been uploaded successfully please wait for the response that shows in your notification page!',
       'Apply for this':'Apply for this',
       'Loan Installment calculator':'Loan Installment calculator',
       'Date of first Installment (yyyy-mm-dd)':'Date of first Installment (yyyy-mm-dd)',
       'please fill-in the form!':'please fill-in the form!',
       'Failed to load transactions':'Failed to load transactions',
       'My loans requests':'My loans requests',
       'Please note that your maximum requests for loans are 3 times':'Please note that your maximum requests for loans are 3 times',
       'Status:':'Status:',
       'If your loan status is ACCEPTED please visit your nearest branch as soon as possible to confirm your loan informations':'If your loan status is ACCEPTED please visit your nearest branch as soon as possible to confirm your loan informations',
       'ATM/Branch locators':'ATM/Branch locators',
       'Failed to load transactions':'Failed to load transactions',
       'Last transactions':'Last transactions',
       '  Account status: Active':'  Account status: Active',
       'If your certificate status is ACCEPTED please visit your nearest branch as soon as possible to confirm informations':'If your certificate status is ACCEPTED please visit your nearest branch as soon as possible to confirm informations',
       'Mini Statements':'Mini Statements',
       'Mini statement shows the last 10 transactions only':'Mini statement shows the last 10 transactions only',
       'Notifications':'Notifications',
       'Important message!':'Important message!',
       'Please come to the bank as soon as possible to fill more information about your loan request':'Please come to the bank as soon as possible to fill more information about your loan request',
       'Transfer\nmoney':'Transfer\nmoney',
       'Mini\nstatements  ':'Mini\nstatements  ',
       'My\ntransactions':'My\ntransactions',
       'Telecom':'Telecom',
       'Water':'Water',
       'My Personal data':'My Personal data',
       'Full name':'Full name',
       'Mobile number':'Mobile number',
       'Email':'Email',
       'National id':'National id',
       'Account type':'Account type',
       'Address':'Address',
       'Job':'Job',
       'Nationality':'Nationality',
       'Marital status':'Marital status',
       'Date of birth':'Date of birth',
       ' Please note, you cannot change your personal data from here, you have to visit your nearest branch\n':' Please note, you cannot change your personal data from here, you have to visit your nearest branch\n',
       'My Profile':'My Profile',
       'Account balance':'Account balance',
       'Personal':'Personal',
       'Personal data':'Personal data',
       'More':'More',
       'Security tips':'Security tips',
       'FAQs retail':'FAQs retail',
       'Contact us':'Contact us',
       'Sign out':'Sign out',
       'Book an appointment':'Book an appointment',
       'Choose your nearest\nbranch':'Choose your nearest\nbranch',
       'Book date':'Book date',
       'Select the purpose':'Select the purpose',
       'Book':'Book',
       'My receipts':'My receipts',
       'YOUR QUEUEING NUMBER IS':'YOUR QUEUEING NUMBER IS',
       'BRANCH':'BRANCH',
       'DATE & TIME':'DATE & TIME',
       'Registration':'Registration',
       'FNB Card Number':'FNB Card Number',
       'National ID':'National ID',
       'Continue':'Continue',
       'Dear customer,\nFor your security, and to ensure you are on the legitimate page of FNB, upon your initial login, you will be asked to enter your username and password then select your preferred authentication type (Face id or OTP). FNB applies strict security rules for Internet Banking Service; however FNB expects you to assume a very important role to protect your information and your money.':'Dear customer,\nFor your security, and to ensure you are on the legitimate page of FNB, upon your initial login, you will be asked to enter your username and password then select your preferred authentication type (Face id or OTP). FNB applies strict security rules for Internet Banking Service; however FNB expects you to assume a very important role to protect your information and your money.',
       'FNB would like to draw your attention to the following precautions:':'FNB would like to draw your attention to the following precautions:',
       '1 - Select a password that is difficult for others to guess.'
           '\n2 - Do not associate your password with anything personal such as birthdays, names,phone numbers.'
           '\n3 - Change your password regularly.'
           '\n4 - Access FNB mobile app from trusted device.'
           '\n5 - Please remember that FNB will never ask you to provide user ID, password, card details, personal information via email, phone or SMS.\n':'1 - Select a password that is difficult for others to guess.'
           '\n2 - Do not associate your password with anything personal such as birthdays, names,phone numbers.'
           '\n3 - Change your password regularly.'
           '\n4 - Access FNB mobile app from trusted device.'
           '\n5 - Please remember that FNB will never ask you to provide user ID, password, card details, personal information via email, phone or SMS.\n',
       'Dark mode':'Dark mode',
       'Change language':'Change language',
       'Telecom type':'Telecom type',
       'Mobile number (To)':'Mobile number (To)',
       'Terms & Conditions':'Terms & Conditions',
       '1 - Security':'1 - Security',
       'The user must take reasonable precautions to prevent unauthorized access to the application and their account information. The user must immediately report any unauthorized access or suspicious activity on their account.':'The user must take reasonable precautions to prevent unauthorized access to the application and their account information. The user must immediately report any unauthorized access or suspicious activity on their account.',
       '2 - User Responsibilities':'2 - User Responsibilities',
       'The user is responsible for maintaining the confidentiality of their login credentials, including their password, and for any actions taken using their account.':'The user is responsible for maintaining the confidentiality of their login credentials, including their password, and for any actions taken using their account.',
       '3 - Transactions:':'3 - Transactions:',
       'The user is responsible for ensuring that all transactions initiated through the application are authorized and accurate.':'The user is responsible for ensuring that all transactions initiated through the application are authorized and accurate.',
       '4 - Fees':'4 - Fees',
       'The user may be charged fees for certain transactions or services provided through the application. The user agrees to pay all applicable fees and charges.':'The user may be charged fees for certain transactions or services provided through the application. The user agrees to pay all applicable fees and charges.',
       '5 - Loan Application':'5 - Loan Application',
       'The user may apply for a loan through the application. The user must provide accurate and complete information when applying for a loan, and the financial institution reserves the right to reject any loan application that does not meet its underwriting criteria.':'The user may apply for a loan through the application. The user must provide accurate and complete information when applying for a loan, and the financial institution reserves the right to reject any loan application that does not meet its underwriting criteria.',
       '6 - Certificates':'6 - Certificates',
       'The financial institution may issue certificates of deposit (CDs) or other similar financial instruments through the application. The user must provide accurate and complete information when opening a CD or other financial instrument.':'The financial institution may issue certificates of deposit (CDs) or other similar financial instruments through the application. The user must provide accurate and complete information when opening a CD or other financial instrument.',
       '7 - Interest Rates':'7 - Interest Rates',
       'The interest rate on a certificate or other financial instrument may be fixed or variable, and may be subject to change at any time without notice.':'The interest rate on a certificate or other financial instrument may be fixed or variable, and may be subject to change at any time without notice.',
       'Transfer money':'Transfer money',
       'Enter the account number':'Enter the account number',
       'Enter the amount':'Enter the amount',
       'Are you sure you want to transfer to on your own responsibility?\n(Please double tap to confirm)':'Are you sure you want to transfer to on your own responsibility?\n(Please double tap to confirm)',
       'Transfer complete':'Transfer complete',
       'Transfer time':'Transfer time',
       'Account number':'Account number',
       'Your new balance 1500 EGP':'Your new balance 1500 EGP',
       'Show/hide':'Show/hide',
       'Currency':'Currency',
       'My receipt':'My receipt',
       'Enter your password (4-digits)':'Enter your password (4-digits)',
       'Important!':'Important!',
       'You get back: EGP ':'You get back: EGP ',
       'Intelligent\n   QA bot':'Intelligent\n   QA bot',
       'Thank you for making a deposit with us. Your account has been credited with the deposited amount.':'Thank you for making a deposit with us. Your account has been credited with the deposited amount.',
'Just a quick message to let you know that your recent deposit has been successfully processed.':'Just a quick message to let you know that your recent deposit has been successfully processed.',
       'Your deposit has been received and credited to your account. Thank you for choosing our bank!':'Your deposit has been received and credited to your account. Thank you for choosing our bank!',
       'Congratulations! Your deposit has been accepted and your account has been updated.':'Congratulations! Your deposit has been accepted and your account has been updated.',
       'We appreciate your business and would like to inform you that your deposit has been processed.':'We appreciate your business and would like to inform you that your deposit has been processed.',
       'Thank you for choosing our bank for your deposit needs. We confirm that your deposit has been processed.':'Thank you for choosing our bank for your deposit needs. We confirm that your deposit has been processed.',
       'Good news! Your deposit has been received and your account balance has been updated accordingly':'Good news! Your deposit has been received and your account balance has been updated accordingly',
       'Your withdrawal request has been processed and the funds have been debited from your account.':'Your withdrawal request has been processed and the funds have been debited from your account.',
       'We have received your withdrawal request and the funds have been transferred to your designated account.':'We have received your withdrawal request and the funds have been transferred to your designated account.',
       'Your withdrawal has been processed and the funds are now available in your account.':'Your withdrawal has been processed and the funds are now available in your account.',
       'Congratulations, your withdrawal has been successfully processed and the funds have been transferred to your designated account.':'Congratulations, your withdrawal has been successfully processed and the funds have been transferred to your designated account.',
       'Your withdrawal request has been processed and the funds have been debited from your account. Thank you for banking with us!':'Your withdrawal request has been processed and the funds have been debited from your account. Thank you for banking with us!',
       'Your loyalty to our bank does not go unnoticed. Thank you for being a valued customer.':'Your loyalty to our bank does not go unnoticed. Thank you for being a valued customer.',
       'We appreciate your trust in us and are always here to meet your banking needs.':'We appreciate your trust in us and are always here to meet your banking needs.',
       'Thank you for choosing our bank. Your continued patronage means a lot to us.':'Thank you for choosing our bank. Your continued patronage means a lot to us.',
       'Your business means a lot to us and we are committed to providing you with the best service possible. ':'Your business means a lot to us and we are committed to providing you with the best service possible. ',
       'We are grateful for your trust in us and thank you for allowing us to serve you':'We are grateful for your trust in us and thank you for allowing us to serve you',
       'Congratulations on earning your certificate! Your hard work has paid off.':'Congratulations on earning your certificate! Your hard work has paid off.',
       'We are proud to recognize your achievements with this certificate. Well done!':'We are proud to recognize your achievements with this certificate. Well done!',
       'Your dedication and commitment have earned you this certificate. Congratulations!':'Your dedication and commitment have earned you this certificate. Congratulations!',
       'We are honored to award you with this certificate. Your achievements are a true inspiration.':'We are honored to award you with this certificate. Your achievements are a true inspiration.',
       'Your commitment to excellence has earned you this certificate. Well done!':'Your commitment to excellence has earned you this certificate. Well done!',
       'Congratulations on earning this certificate. Your achievements are a testament to your hard work and dedication.':'Congratulations on earning this certificate. Your achievements are a testament to your hard work and dedication.',
       'We have an exclusive offer just for you. Visit us today to take advantage of this limited-time deal.':'We have an exclusive offer just for you. Visit us today to take advantage of this limited-time deal.',
       'We have an amazing offer on cards. Visit us today to take advantage of this incredible deal.':'We have an amazing offer on cards. Visit us today to take advantage of this incredible deal.',
       'You deserve something special! Check out our latest offer on certificates and treat yourself today.':'You deserve something special! Check out our latest offer on certificates and treat yourself today.',
       'We are thrilled to offer you this exclusive promotion on [product/service]. Visit us today to learn more.':'We are thrilled to offer you this exclusive promotion on [product/service]. Visit us today to learn more.',
       'Need funds for a big purchase or unexpected expense? We can help! Contact us today to learn about our loan options.':'Need funds for a big purchase or unexpected expense? We can help! Contact us today to learn about our loan options.',
       'Looking to start a new business or expand your current one? We offer business loans to help you achieve your goals.':'Looking to start a new business or expand your current one? We offer business loans to help you achieve your goals.',
       'Need a personal loan for a home renovation or vacation? We have flexible loan options to fit your needs.':'Need a personal loan for a home renovation or vacation? We have flexible loan options to fit your needs.',
       'We understand that unexpected expenses can arise. Our loan options can help you get the funds you need, when you need them.':'We understand that unexpected expenses can arise. Our loan options can help you get the funds you need, when you need them.',
       'Our loan experts are here to help you navigate the lending process and find the right loan for your needs.':'Our loan experts are here to help you navigate the lending process and find the right loan for your needs.',
       'Want to consolidate your debt or improve your credit score? Our loan options can help you get on the path to financial stability.':'Want to consolidate your debt or improve your credit score? Our loan options can help you get on the path to financial stability.',
       'Deposit':'Deposit',
       'Withdrawal':'Withdrawal',
       'Compliment ':'Compliment ',
       'Offers':'Offers',
       'Feedback':'Feedback',
       'Something is error, please try again later':'Something is error, please try again later',
       'We value your opinion and would love to hear about your experience with us. Please feel free to share your thoughts and suggestions with us on how we can serve you better. We appreciate your time and look forward to hearing from you.':'We value your opinion and would love to hear about your experience with us. Please feel free to share your thoughts and suggestions with us on how we can serve you better. We appreciate your time and look forward to hearing from you.',
       'Please type/voice your feedback.':'Please type/voice your feedback.',





     },
    'ar_SU' :{
      'Username' : 'اسم المستخدم',
      'Password' : 'كلمة المرور',
      'Create account': 'انشاء حساب',
      'FNB account number':'رقم الحساب',
      'Login Successful':'تم تسجيل الدخول بنجاح',
      'Please enter your name & password!':'الرجاء إدخال اسمك وكلمة المرور!',
      'You entered incorrect username or password, please try again!':'لقد أدخلت اسم مستخدم أو كلمة مرور غير صحيحة ، يرجى المحاولة مرة أخرى!',
      'Login':'تسجيل الدخول',
      'Register new user':'تسجيل مستخدم جديد',
      'FAQs\nretail':'الأسئلة الشائعة',
      '  Foreign\nExchange':'سعر العملات',
      ' ATM/Branch\n     Locator':'الفروع والماكينات',
      'Contact\n     us':'تواصل معانا',
      'Authentication':'إثبات الشخصية',
      'Choose the authentication type to log-in':'اختر نوع اثبات الشخصية لتسجيل الدخول',
      'Face id':'بصمة الوجه',
      'otp sent!':'تم ارسال الرقم السري المتغير',
      'invalid email!':'بريد إلكتروني خاطئ!',
      'OTP':' الرقم السري المتغير',
      'OTP authentication':'تاكيد الرقم السري المتغير',
      'A verification code has been sent to':'تم إرسال رمز التحقق إلى',
      'Welcome ☺':'مرحبا ☺ً',
      'Incorrect OTP!':'الرقم السري المتغير غير صحيح!',
      'Confirm':'تأكد',
      'Error':'خطأ',
      'Success':'نجاح',
      'Acceptable process!':'عملية مقبولة!',
      'error':'خطأ',
      'Certificate':'شهادة',
      'Select product':'حدد الشهادة',
      'Amount':'المبلغ',
      'Enter your password (4 digits)':'أدخل كلمة المرور الخاصة بك (4 أرقام)',
      'Start date':'تاريخ البدء',
      'I have read and agree to the terms\nof FNB services':'FNB لقد قرأت ووافقت على شروط ',
      'Are you sure you want to apply for this certificate informations?':'هل أنت متأكد أنك تريد التقدم للحصول على هذه الشهادة المعلومات؟',
      'Yes':'نعم',
      'Acceptable process!':'عملية مقبولة!',
      'No enough balance in your account!':'لا يوجد رصيد كاف في حسابك!',
      'Incorrect password':'كلمة سر خاطئة',
      'Please fill-in the form and agree to the terms!':'يرجى ملء النموذج والموافقة على الشروط!',
      'Apply':'طلب',
      'Already Exists':'موجود بالفعل',
      'Change password':'تغيير كلمة المرور',
      'Current password':'كلمة السر الحالية',
      'New password':'كلمة المرور الجديدة',
      'Confirm password':'تأكيد كلمة المرور',
      'Password changed successfully':'تم تغيير كلمة المرور بنجاح',
      'Please fill in the form!':'يرجى تعبئة النموذج!',
      'The old password is not correct':'كلمة المرور القديمة غير صحيحة',
      'Please check that you entered data correctly!':'يرجى التحقق من أنك أدخلت البيانات بشكل صحيح!',
      'Save changes':'احفظ التغييرات',
      'Please verify your identity':'يرجى التحقق من هويتك',
      'Account created successfully!':'الحساب اقيم بنجاح!',
      'Please check that you entered the confirm password correctly!':'يرجى التحقق من إدخال كلمة المرور بشكل صحيح!',
      'Please agree to the terms and conditions of FNB services!':'الرجاء الموافقة على شروط وأحكام خدمات FNB!',
      'You miss to enter something!':'لقد فاتتك لإدخال شيء ما!',
      'Please check that you entered the confirm password correctly and agree to the terms and conditions of FNB services!':'يرجى التحقق من إدخال كلمة المرور بشكل صحيح والموافقة على شروط وأحكام خدمات FNB!',
      'Something is wrong!':'هناك شئ غير صحيح!',
      'Create':'إنشاء',
      'Currencies':'العملات',
      'Exhange rates':'معدل التحويل',
      'Currency converter':'محول العملات',
      'Home':'الصفحه الرئيسيه',
      'Payments':'المدفوعات',
      'Profile':'الصفحه الشخصيه',
      'Currency Converter':'محول العملات',
      'Input Value to Convert':'قيمة الإدخال المراد تحويلها',
      'From':'من',
      'To':'الي',
      'Result':'النتيجة',
      'Term Deposit Calculator':'حاسبة الودائع',
      'How much would you like to deposit?':'كم مبلغ تريد ايداعه؟',
      'Amount':'المبلغ',
      'Duration (months)':'المدة (شهور)',
      'Interest rate (%)':'سعر الفائدة (٪)',
      'Calculate':'احسب',
      'Future University in Egypt':'جامعة المستقبل في مصر',
      'British University in Egypt':'الجامعة البريطانية في مصر',
      'Ahram Canadian University':'جامعة الاهرام الكندية',
      'Ain shams University':'جامعة عين شمس',
      'Alexandria':'الإسكندرية',
      'American University in Egypt':'الجامعة الأمريكية في مصر',
      'Cairo University':'جامعة القاهرة',
      'Al Azhar University':'جامعة الأزهر',
      'Badr University':'جامعة بدر',
      'accnum':'رقم حساب',
      'balance':'رصيد حساب',
      'Education':'تعليم',
      'Education name':'اسم التعليم',
      'Student National ID':'الرقم القومي للطالب',
      'Purpose':'غاية',
      'Enter your password (4 digits)':'أدخل كلمة المرور الخاصة بك (4 أرقام)',
      'Are you sure you want to transfer on your own responsibility?':'هل أنت متأكد أنك تريد التحويل على مسؤوليتك الخاصة؟',
      'Not enough balance in your account!':'لا يوجد رصيد كاف في حسابك!',
      'Incorrect password':'كلمة سر خاطئة',
      'Please fill-in the form!':'يرجى تعبئة النموذج!',
      'Transfer':'تحويل',
      'Injas Electricity':'انجاس للكهرباء',
      'Canal Electricity':'كانيل للكهرباء',
      'Middle Egypt Electricity':'كهرباء مصر الوسطى',
      'North Delta Electricity':'كهرباء شمال الدلتا',
      'North Cairo Electricity':'شمال القاهرة للكهرباء',
      'South Delta Electricity':'كهرباء جنوب الدلتا',
      'Electricity':'كهرباء',
      'Service provider':'مقدم الخدمة',
      'Your electricity code number':'رقم رمز الكهرباء الخاص بك',
      'Egyptian pound exchange':'صرف الجنيه المصري',
      'Input value in egyptian pound':'قيمة المدخلات بالجنيه المصري',
      'Sell':'بيع',
      'Buy':'شراء',
      'Call us':'اتصل بنا',
      'tel':'هاتف',
      'cant launch this url':'لا يمكن تحميل هذا url',
      'Call':'اتصل',
      'accountnumber':'رقم حساب',
      'FAQs - Retail':'أسئلة وأجوبة - سرد',
      'Can i change my user iD?':'هل يمكنني تغيير رقمي الخاص؟',
      'You can not change your user ID':'لا يمكنك تغيير رقمك الخاص',
      'When can i use FNB app?':'متى يمكنني استخدام تطبيق FNB؟',
      'FNB app is available 24/7':'تطبيق FNB متاح طوال اليوم',
      'Can the "Login password" be changed?':'هل يمكن تغيير "كلمة مرور تسجيل الدخول"؟',
      'Yes, you can change the "Login password" by clicking on the settings then Change password':'نعم ، يمكنك تغيير "كلمة مرور تسجيل الدخول" من خلال النقر على الإعدادات ثم تغيير كلمة المرور',
      'How can i login via One-Time-Password?':'كيف يمكنني تسجيل الدخول باستخدام كلمة مرور لمرة واحدة؟',
      'Once you clicking on the OTP option you will receive 4 digits through your mobile number, enter these digits on the textfield to login':'بمجرد النقر فوق خيار OTP ، ستتلقى 4 أرقام من خلال رقم هاتفك المحمول ، أدخل هذه الأرقام في حقل النص لتسجيل الدخول',
      'Can i change my personal information through the application?':'هل يمكنني تغيير معلوماتي الشخصية من خلال التطبيق؟',
      'No, you can not update/change you personal information unless you go to any bank branch':'لا ، لا يمكنك تحديث / تغيير معلوماتك الشخصية إلا إذا ذهبت إلى أي فرع من فروع البنوك',
      'Can i cancel the book appointment to visit a branch?':'هل يمكنني إلغاء موعد الحجز لزيارة الفرع؟',
      'Yes, you can cancel your request anytime':'نعم ، يمكنك إلغاء طلبك في أي وقت',
      'Can transfers be made to other accounts inside or outside FNB?':'هل يمكن إجراء التحويلات إلى حسابات أخرى داخل FNB أو خارجه؟',
      'You can transfer to FNB accounts only':'يمكنك التحويل إلى حسابات FNB فقط',
      'Ok':'حسنا',
      'TAQA GAS':'طاقة غاز',
      'Gastec':'جاستيك',
      'Master Gas':'ماستر غاز',
      'Gas':'غاز',
      'Fawry account number':'رقم حساب فوري',
      'Current reading':'القراءة الحالية',
      'Queuing request':'طلب الانتظار',
      'Deposit calculator':'حاسبة الودائع',
      'Newsroom':'الأخبار',
      'Locations':'المواقع',
      'Settings':'إعدادات',
      'Accounts':'حسابات',
      'Cards':'البطاقات',
      'Loans':'القروض',
      'Certificates':'الشهادات',
      'Account':'حساب',
      'Enter your pass':'ادخل رقمك السري',
      'My card':'بطاقتي',
      'Credit':'بطاقة إئتمان',
      'Name':'الاسم',
      'Cards offers':'عروض البطاقات',
      'Debit':'بطاقة ائتمان',
      'Maximum Credit Limit : 250,000 EGP':'الحد الأقصى للائتمان: 250،000 جنيه مصري',
      'Grace period : up to 57 days for purchase':'فترة السماح: تصل إلى 57 يومًا للشراء',
      'Gold':'ذهب',
      'Maximum Credit Limit : 100,000 EGP':'الحد الأقصى للائتمان: 100،000 جنيه مصري',
      'Online card usage : available':'استخدام البطاقة عبر الإنترنت: متوفر',
      'Card usage : locally and abroad':'استخدام البطاقة: محليًا وخارجيًا',
      'Loan amount calculator':'حاسبة مبلغ القرض',
      'Loan installment calculator':'حاسبة أقساط القرض',
      'My loans requests':'طلبات القروض',
      'Time to invest!':'حان وقت الاستثمار',
      'It seems that you dont have any investment products yet!':'يبدو أنه ليس لديك أي منتجات استثمارية حتى الآن!',
      'Apply':'طلب',
      'My certificates':'شهاداتي',
      'Your loan request has been uploaded successfully please wait for the response that shows in your notification page!':'تم تحميل طلب القرض الخاص بك بنجاح ، يرجى انتظار الرد الذي يظهر في صفحة الإشعارات الخاصة بك!',
      'Already Exists':'موجود أصلا',
      'Your maximum requests for loans are 3, you need to visit your nearest branch to solve this problem!':'الحد الأقصى لطلبات القروض الخاصة بك هو 3 ، تحتاج إلى زيارة أقرب فرع لك لحل هذه المشكلة!',
      'Loan amount':'مبلغ القرض',
      'Min 5000 EGP':'5000 جنيه كحد أدنى',
      'Max 1,500,000 EGP':'بحد أقصى 1،500،000 ج',
      'Loan period':'فترة القرض',
      'Min 6 months':'6 أشهر على الأقل',
      'Max 120 months':'120 شهرًا كحد أقصى',
      'Interest rate (Annual %)':'معدل الفائدة (٪ سنوية)',
      'Min 16%':'16٪ كحد أدنى',
      'Max 21%':'21٪ كحد أقصى',
      'please check the constraints of the form!':'الرجاء التحقق من قيود النموذج!',
      'Your monthly payments':'دفعاتك الشهرية',
      'Total payable':'إجمالي المدفوعات',
      'Total interest':'مجموع الفوائد',
      '* Please note that your maximum requests for loans are 3 times':'* يرجى الملاحظة أن الحد الأقصى لطلبات القروض الخاصة بك هو 3 مرات',
      'Your loan request has been uploaded successfully please wait for the response that shows in your notification page!':'تم تحميل طلب القرض الخاص بك بنجاح ، يرجى انتظار الرد الذي يظهر في صفحة الإشعارات الخاصة بك!',
      'Apply for this':'تقدم بطلب للحصول على هذا',
      'Loan Installment calculator':'حاسبة أقساط القرض',
      'Date of first Installment (yyyy-mm-dd)':'تاريخ القسط الأول (yyyy-mm-dd)',
      'please fill-in the form!':'يرجى تعبئة النموذج!',
      'Failed to load transactions':'فشل تحميل المعاملات',
      'My loans requests':'طلبات القروض',
      'Please note that your maximum requests for loans are 3 times':'يرجى الملاحظة أن الحد الأقصى لطلبات القروض الخاصة بك هو 3 مرات',
      'Status:':'حالة:',
      'If your loan status is ACCEPTED please visit your nearest branch as soon as possible to confirm your loan informations':'إذا تم قبول حالة القرض الخاص بك ، فيرجى زيارة أقرب فرع إليك في أقرب وقت ممكن لتأكيد معلومات القرض الخاص بك',
      'ATM/Branch locators':'تحديد مواقع أجهزة الصراف الآلي / الفروع',
      'Failed to load transactions':'فشل تحميل المعاملات',
      'Last transactions':'آخر المعاملات',
      '  Account status: Active':'حالة الحساب: نشط',
      'If your certificate status is ACCEPTED please visit your nearest branch as soon as possible to confirm informations':'إذا تم قبول حالة شهادتك ، يرجى زيارة أقرب فرع إليك في أقرب وقت ممكن لتأكيد المعلومات',
      'Mini Statements':'بيانات مصغرة',
      'Mini statement shows the last 10 transactions only':'يُظهر كشف الحساب المصغر آخر 10 معاملات فقط',
      'Notifications':'إشعارات',
      'Important message!':'رسالة مهمة!',
      'Please come to the bank as soon as possible to fill more information about your loan request':'يرجى الحضور إلى البنك في أقرب وقت ممكن لملء مزيد من المعلومات حول طلب القرض الخاص بك',
      'Transfer\nmoney':'تحويل\n أموال',
      'Mini\nstatements  ':'بيانات\n مصغرة',
      'My\ntransactions':'معاملاتي',
      'Telecom':'اتصالات',
      'Water':'ماء',
      'My Personal data':'بياناتي الشخصية',
      'Full name':'الاسم الكامل',
      'Mobile number':'رقم الهاتف المحمول',
      'Email':'بريد إلكتروني',
      'National id':'رقم الهوية',
      'Account type':'نوع الحساب',
      'Address':'عنوان',
      'Job':'وظيفة',
      'Nationality':'جنسية',
      'Marital status':'الحالة الاجتماعية',
      'Date of birth':'تاريخ الميلاد',
      ' Please note, you cannot change your personal data from here, you have to visit your nearest branch\n':'يرجى الملاحظة أنه لا يمكنك تغيير بياناتك الشخصية من هنا ، عليك زيارة أقرب فرع لك ',
      'My Profile':'الصفحه الشخصيه',
      'Account balance':'رصيد الحساب',
      'Personal':'شخصي',
      'Personal data':'بيانات شخصية',
      'More':'أكثر',
      'Security tips':'نصائح أمنية',
      'FAQs retail':'أسئلة وأجوبة البيع بالتجزئة',
      'Contact us':'اتصل بنا',
      'Sign out':'تسجيل الخروج',
      'Book an appointment':'احجز موعدًا',
      'Choose your nearest\nbranch':'اختر أقرب فرع لك',
      'Book date':'تاريخ الحجز',
      'Select the purpose':'حدد الغرض',
      'Book':'الحجز',
      'My receipts':'إيصالاتي',
      'YOUR QUEUEING NUMBER IS':'رقم قائمة الانتظار الخاص بك هو',
      'BRANCH':'فرع',
      'DATE & TIME':'التاريخ والوقت',
      'Registration':'تسجيل',
      'FNB Card Number':'رقم بطاقة FNB',
      'National ID':'رقم الهوية',
      'Continue':'أكمل',
      'Dear customer,\nFor your security, and to ensure you are on the legitimate page of FNB, upon your initial login, you will be asked to enter your username and password then select your preferred authentication type (Face id or OTP). FNB applies strict security rules for Internet Banking Service; however FNB expects you to assume a very important role to protect your information and your money.':'عزيزي العميل ، \n من أجل أمانك ، وللتأكد من وجودك على الصفحة الشرعية لـ FNB ، عند تسجيل الدخول الأولي ، سيُطلب منك إدخال اسم المستخدم وكلمة المرور الخاصين بك ثم تحديد نوع المصادقة المفضل لديك (معرف الوجه أو OTP). يطبق FNB قواعد أمان صارمة للخدمات المصرفية عبر الإنترنت ؛ لكن FNB تتوقع منك أن تقوم بدور مهم للغاية لحماية معلوماتك وأموالك.',
      'FNB would like to draw your attention to the following precautions:':'يود FNB لفت انتباهك إلى الاحتياطات التالية:',
      '1 - Select a password that is difficult for others to guess.'
          '\n2 - Do not associate your password with anything personal such as birthdays, names,phone numbers.'
          '\n3 - Change your password regularly.'
          '\n4 - Access FNB mobile app from trusted device.'
          '\n5 - Please remember that FNB will never ask you to provide user ID, password, card details, personal information via email, phone or SMS.\n':'1 - حدد كلمة مرور يصعب على الآخرين تخمينها.'
  "\n2 - لا تربط كلمة مرورك بأي شيء شخصي مثل أعياد الميلاد والأسماء وأرقام الهواتف."
  "\n3 - غيّر كلمة المرور بانتظام."
  "\n4 - الوصول إلى تطبيق FNB للجوال من جهاز موثوق به."
  "\n5 - يرجى تذكر أن FNB لن يطلب منك أبدًا تقديم معرف المستخدم أو كلمة المرور أو تفاصيل البطاقة أو المعلومات الشخصية عبر البريد الإلكتروني أو الهاتف أو الرسائل القصيرة. \n'",
      'Dark mode':'الوضع المظلم',
      'Change language':'تغيير اللغة',
      'Telecom type':'نوع الاتصالات',
      'Mobile number (To)':'رقم الهاتف المحمول (إلى)',
      'Terms & Conditions':'البنود و الظروف',
      '1 - Security':'1 - الأمن',
      'The user must take reasonable precautions to prevent unauthorized access to the application and their account information. The user must immediately report any unauthorized access or suspicious activity on their account.':'يجب على المستخدم اتخاذ الاحتياطات المعقولة لمنع الوصول غير المصرح به إلى التطبيق ومعلومات حسابه. يجب على المستخدم الإبلاغ فورًا عن أي وصول غير مصرح به أو نشاط مشبوه على حسابه.',
      '2 - User Responsibilities':'2 - مسؤوليات المستخدم',
      'The user is responsible for maintaining the confidentiality of their login credentials, including their password, and for any actions taken using their account.':'يتحمل المستخدم مسؤولية الحفاظ على سرية بيانات اعتماد تسجيل الدخول الخاصة به ، بما في ذلك كلمة المرور الخاصة به ، وعن أي إجراءات يتم اتخاذها باستخدام حسابه.',
      '3 - Transactions:':'3 - المعاملات:',
      'The user is responsible for ensuring that all transactions initiated through the application are authorized and accurate.':'يتحمل المستخدم مسؤولية التأكد من أن جميع المعاملات التي تتم من خلال التطبيق مصرح بها ودقيقة.',
      '4 - Fees':'4 - الرسوم',
      'The user may be charged fees for certain transactions or services provided through the application. The user agrees to pay all applicable fees and charges.':'قد يتم فرض رسوم على المستخدم مقابل معاملات أو خدمات معينة مقدمة من خلال التطبيق. يوافق المستخدم على دفع جميع الرسوم والتكاليف المطبقة.',
      '5 - Loan Application':'5 - طلب القرض',
      'The user may apply for a loan through the application. The user must provide accurate and complete information when applying for a loan, and the financial institution reserves the right to reject any loan application that does not meet its underwriting criteria.':'يمكن للمستخدم التقدم بطلب للحصول على قرض من خلال التطبيق. يجب على المستخدم تقديم معلومات دقيقة وكاملة عند التقدم للحصول على قرض ، وتحتفظ المؤسسة المالية بالحق في رفض أي طلب قرض لا يفي بمعايير الاكتتاب الخاصة بها.',
      '6 - Certificates':'6 - الشهادات',
      'The financial institution may issue certificates of deposit (CDs) or other similar financial instruments through the application. The user must provide accurate and complete information when opening a CD or other financial instrument.':'يجوز للمؤسسة المالية إصدار شهادات إيداع (CD) أو غيرها من الأدوات المالية المماثلة من خلال التطبيق. يجب على المستخدم تقديم معلومات دقيقة وكاملة عند فتح قرص مضغوط أو أي أداة مالية أخرى.',
      '7 - Interest Rates':'7 - أسعار الفائدة',
      'The interest rate on a certificate or other financial instrument may be fixed or variable, and may be subject to change at any time without notice.':'قد يكون سعر الفائدة على شهادة أو أداة مالية أخرى ثابتًا أو متغيرًا ، وقد يخضع للتغيير في أي وقت دون إشعار.',
      'Transfer money':'تحويل أموال',
      'Enter the account number':'أدخل رقم الحساب',
      'Enter the amount':'أدخل المبلغ',
      'Are you sure you want to transfer to on your own responsibility?\n(Please double tap to confirm)':'هل أنت متأكد أنك تريد التحويل إلى على مسؤوليتك الخاصة؟ \n (الرجاء النقر مرتين للتأكيد)',
      'Transfer complete':'اكتمل النقل',
      'Transfer time':'وقت النقل',
      'Account number':'رقم حساب',
      'Your new balance 1500 EGP':'رصيدك الجديد 1500 جنيه',
      'Show/hide':'اظهار/اخفاء',
      'Currency':'عملة',
      'My receipt':'إيصال',
      'Enter your password (4-digits)':'أدخل كلمة المرور الخاصة بك (4 أرقام)',
      'Important!':'هام!',
      'You get back: EGP ':'العائد بالجنية',
      'Intelligent\n   QA bot':'بوت ذكي',
      'Thank you for making a deposit with us. Your account has been credited with the deposited amount.':'شكراً لك على إيداعك لدينا. تم إضافة المبلغ المودع إلى حسابك.',
      'Just a quick message to let you know that your recent deposit has been successfully processed.':'رسالة سريعة لإعلامك بأن إيداعك الأخير تم بنجاح.',
      'Your deposit has been received and credited to your account. Thank you for choosing our bank!':'لقد تم استلام إيداعك وتم إضافته إلى حسابك. شكراً لاختياركم بنكنا!',
      'Congratulations! Your deposit has been accepted and your account has been updated.':'تهانينا! تم قبول إيداعك وتم تحديث حسابك.',
      'We appreciate your business and would like to inform you that your deposit has been processed.':'نقدر تعاملك معنا ونود إعلامك بأن تم إيداعك.',
      'Thank you for choosing our bank for your deposit needs. We confirm that your deposit has been processed.':'شكراً لاختيارك بنكنا لتلبية احتياجاتك من الإيداعات. نؤكد لك أنه تم معالجة إيداعك.',
      'Good news! Your deposit has been received and your account balance has been updated accordingly':'أخبار جيدة! تم استلام إيداعك وتم تحديث رصيد حسابك وفقاً لذلك.',
      'Your withdrawal request has been processed and the funds have been debited from your account.':'تم معالجة طلب السحب الخاص بك وتم خصم الأموال من حسابك.',
      'We have received your withdrawal request and the funds have been transferred to your designated account.':'لقد تلقينا طلب السحب الخاص بك وتم تحويل الأموال إلى الحساب المحدد الخاص بك.',
      'Your withdrawal has been processed and the funds are now available in your account.':'تم معالجة طلب السحب الخاص بك والأموال متاحة الآن في حسابك.',
      'Congratulations, your withdrawal has been successfully processed and the funds have been transferred to your designated account.':'تهانينا، تم معالجة طلب السحب الخاص بك بنجاح وتم تحويل الأموال إلى الحساب المحدد الخاص بك.',
      'Your withdrawal request has been processed and the funds have been debited from your account. Thank you for banking with us!':'تم معالجة طلب السحب الخاص بك وتم خصم الأموال من حسابك. شكراً لاختيارك بنكنا!',
      'Your loyalty to our bank does not go unnoticed. Thank you for being a valued customer.':'نحن نلاحظ ولاءك لبنكنا. شكراً لك على كونك عميلًا ثمينًا بالنسبة لنا.',
      'We appreciate your trust in us and are always here to meet your banking needs.':'نحن نقدر ثقتك بنا ونحن دائماً هنا لتلبية احتياجاتك المصرفية.',
      'Thank you for choosing our bank. Your continued patronage means a lot to us.':'شكرًا لك على اختيار بنكنا. استمرارك في التعامل معنا يعني الكثير بالنسبة لنا.',
      'Your business means a lot to us and we are committed to providing you with the best service possible. ':'تعاملك معنا يعني الكثير بالنسبة لنا ونحن ملتزمون بتقديم أفضل خدمة ممكنة لك.',
      'We are grateful for your trust in us and thank you for allowing us to serve you':'نحن ممتنون لثقتك بنا ونشكرك على السماح لنا بخدمتك.',
      'Congratulations on earning your certificate! Your hard work has paid off.':'تهانينا على حصولك على الشهادة! لقد دفع عملك الشاق ثماره.',
      'We are proud to recognize your achievements with this certificate. Well done!':'نحن فخورون بالاعتراف بإنجازاتك من خلال هذه الشهادة. عمل جيد!',
      'Your dedication and commitment have earned you this certificate. Congratulations!':'لقد حققت هذه الشهادة بفضل اجتهادك والتزامك. تهانينا!',
      'We are honored to award you with this certificate. Your achievements are a true inspiration.':'نحن متشرفون بمنحك هذه الشهادة. إن إنجازاتك هي مصدر إلهام حقيقي',
      'Your commitment to excellence has earned you this certificate. Well done!':'لقد حققت هذه الشهادة بفضل التزامك بالتميز. عمل جيد!',
      'Congratulations on earning this certificate. Your achievements are a testament to your hard work and dedication.':'تهانينا على حصولك على هذه الشهادة. إن إنجازاتك هي دليل على عملك الشاق والتفاني',
      'We have an exclusive offer just for you. Visit us today to take advantage of this limited-time deal.':'لدينا عرض حصري خاص بك فقط. قم بزيارتنا اليوم للاستفادة من هذا العرض لفترة محدودة.',
      'We have an amazing offer on cards. Visit us today to take advantage of this incredible deal.':'لدينا عرض مذهل على البطاقات. قم بزيارتنا اليوم للاستفادة من هذا العرض الرائع',
      'You deserve something special! Check out our latest offer on certificates and treat yourself today.':'أنت تستحق شيئًا خاصًا! تحقق من عرضنا الأخير على الشهادات وامنح نفسك مكافأة اليوم',
      'We are thrilled to offer you this exclusive promotion on [product/service]. Visit us today to learn more.':'نحن متحمسون لتقديم لك هذا العرض الحصري على [المنتج / الخدمة]. قم بزيارتنا اليوم لمعرفة المزيد',
      'Need funds for a big purchase or unexpected expense? We can help! Contact us today to learn about our loan options.':'هل تحتاج إلى الأموال لشراء كبير أو مصاريف غير متوقعة؟ يمكننا المساعدة! اتصل بنا اليوم لمعرفة خيارات القروض التي نقدمها',
      'Looking to start a new business or expand your current one? We offer business loans to help you achieve your goals.':'هل تبحث عن بدء عمل تجاري جديد أو توسيع عملك الحالي؟ نحن نقدم قروض الأعمال لمساعدتك على تحقيق أهدافك',
      'Need a personal loan for a home renovation or vacation? We have flexible loan options to fit your needs.':'هل تحتاج إلى قرض شخصي لتجديد منزلك أو لقضاء عطلة؟ لدينا خيارات قروض مرنة تتناسب مع احتياجاتك',
      'We understand that unexpected expenses can arise. Our loan options can help you get the funds you need, when you need them.':'نحن نفهم أن المصاريف غير المتوقعة قد تنشأ في أي وقت. خيارات القروض التي نقدمها يمكنها مساعدتك في الحصول على الأموال التي تحتاج إليها، عندما تحتاج إليها.',
      'Our loan experts are here to help you navigate the lending process and find the right loan for your needs.':'خبراؤنا في مجال القروض هنا لمساعدتك في التنقل في عملية الإقراض والعثور على القرض المناسب لاحتياجاتك',
      'Want to consolidate your debt or improve your credit score? Our loan options can help you get on the path to financial stability.':'هل ترغب في دمج ديونك أو تحسين درجة الائتمان الخاصة بك؟ خيارات القروض التي نقدمها يمكنها مساعدتك على الوصول إلى الاستقرار المالي',
      'Deposit':'مدفوعات',
      'Withdrawal':'سحب',
      'Compliment ':'إطراء',
      'Offers':'عروض',
      'Feedback':'ردود الفعل',
      'Something is error, please try again later':'حدث خطأ ما، يرجى المحاولة مرة أخرى لاحقًا',
      'We value your opinion and would love to hear about your experience with us. Please feel free to share your thoughts and suggestions with us on how we can serve you better. We appreciate your time and look forward to hearing from you.':'حن نقدر رأيك ونرغب في الاطلاع على تجربتك معنا. يرجى الاطمئنان بأنك حر في التعبير عن أفكارك واقتراحاتك حول كيفية خدمتك بشكل أفضل. نقدر وقتك ونتطلع إلى الاستماع منك.',
      'Please type/voice your feedback.':'يرجى كتابة/تسجيل ملاحظاتك.',
      '':'',
      '':'',
      '':'',
      '':'',
      '':'',



    },
  };

}