/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData plug_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_lightning_bolt = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gas_burner = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_recognition = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frequently_asked_questions = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_radius = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_black = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xf084, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_alt = IconData(0xf3cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
